### ISSUE TITLE
make `specta(remote)` act like `serde(remote)`

### ISSUE THREAD

**Issue by Brendonovich** [specta-rs/specta#26]

**Comment by cathaysia** [comment]
if specta using difference type with serde, should it skip these attribute so avoid conflict with serde?

**Comment by oscartbeaumont** [comment]
We must support Serde attributes as if the Serde behaviour and Specta types mismatch you've got zero typesafety. For attributes we can't properly support we are going to take a conservative default (this part isn't implemented yet but planned). Eg. ’with‘ being set will cause the type to become ‘Unknown‘ unless you override it back because Specta can't be sure of what your ‘with‘ function does.
