### ISSUE TITLE
`&'a [&'a str]` become `string` instead of `string[]`

### ISSUE THREAD

**Issue by anatawa12** [specta-rs/specta#281]
I'm using 2.0.0-rc.20

I tried export the following type to typescript through `tauri-specta`

```rust
#[derive(Serialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct GlobalInfo<'a> {
    language: &'a str,
    theme: &'a str,
    version: Option<&'a str>,
    commit_hash: Option<&'a str>,
    os_type: &'a str,
    arch: &'a str,
    os_info: &'a str,
    webview_version: &'a str,
    local_app_data: &'a str,
    default_unity_arguments: &'a [&'a str],
}
```

but it generates type like this

```
export type GlobalInfo = { language: string; theme: string; version: string | null; commitHash: string | null; osType: string; arch: string; osInfo: string; webviewVersion: string; localAppData: string; defaultUnityArguments: string }
```

In this type, `defaultUnityArguments` (in rust `default_unity_arguments:  &'a [&'a str]`) should be `string[]` because array of string, but specta generates string

**Comment by oscartbeaumont** [comment]
For some reason `assert_ts!(&[&str], "string[]");` works but when the type is put in a struct it breaks so that explained how this wasn't noticed earlier.

The bug is [this implementation](https://github.com/specta-rs/specta/blob/13c74804f510d4002c58750717e6c532effdfa87/specta/src/type/impls.rs#L39) as we passthrough to `T` and not `Vec<T>`.

**Comment by anatawa12** [comment]
it has been 4 month since last RC release but no new RC release was pushed. Could you push new RC release, please?
